# Generated by Django 3.1.3 on 2020-11-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('RutC', models.AutoField(primary_key=True, serialize=False, verbose_name='Rut -')),
                ('Nombres', models.CharField(max_length=70, verbose_name='Nombre ')),
                ('Apellidos', models.CharField(max_length=70, verbose_name='Apellido -')),
                ('Direccion', models.CharField(max_length=70, verbose_name='Direccion -')),
                ('Fono', models.IntegerField(verbose_name='Numero contacto -')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email -')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('CodigoP', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo -')),
                ('NombreP', models.CharField(max_length=35, verbose_name='Nombre del producto -')),
                ('PrecioP', models.IntegerField(verbose_name='Precio -')),
                ('Descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion -')),
                ('Imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('NumPedido', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de pedido -')),
                ('Estado', models.BooleanField(verbose_name='Estado -')),
                ('Fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pedido -')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente', verbose_name='Cliente -')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto', verbose_name='Producto -')),
            ],
        ),
    ]
